# Configure of jekyll

# github default configurations
safe: true
lsi: false
pygments: true

# override jekyll configurations
markdown: rdiscount

# My configurations
title: 桂糊涂的流水账
ga: UA-22960361-1 
