# Configure of jekyll

# github default configurations
safe: true
lsi: false
pygments: true

# override jekyll configurations
# markdown: rdiscount
markdown: redcarpet

# My configurations
title: 桂糊涂的流水账
ga: UA-22960361-1 
url: http://guileen.github.com
author: Jason Gui
email: guileen AT gmail DOT com
